apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: yahav2305/counter:latest
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 50m
            memory: "64Mi"