apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 60