name: Production Workflow
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
jobs:
  docker-build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/counter:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy-to-prod-namespace:
    runs-on: ubuntu-22.04
    needs: [docker-build-and-push]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v4
      with:
        version: '1.29'
      id: install
    - uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Deploy to prod namespace
      # If deployment doensn't exist, create it. If it does, update the image
      run: |
        kubectl get deployment counter &>/dev/null && kubectl set image deployment/counter counter=${{ vars.DOCKERHUB_USERNAME }}/counter:${{ github.sha }} || kubectl apply -f ./infra/deploy.yaml