name: Production Workflow
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.15.3'
      id: install
    - name: Lint helm chart
      run: helm lint ./infra/helm/counter --values ./infra/helm/values/counter.yaml
  docker-build-and-push:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.ECR }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  helm-package-and-push:
    runs-on: ubuntu-22.04
    needs: test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: eu-north-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.15.3'
      id: install
    - name: Package helm chart
      run: |
        helm package ./infra/helm/counter --version 1.0.0-${{ github.sha }} --app-version ${{ github.sha }}
    - name: Push helm chart to GHCR
      run: helm push ./counter-1.0.0-${{ github.sha }}.tgz oci://${{ vars.ECR }}
  deploy-to-prod-namespace:
    runs-on: ubuntu-22.04
    needs: [docker-build-and-push, helm-package-and-push]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.2.0
      with:
         version: 'v3.15.3'
      id: install
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: eu-north-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
    - name: Deploy counter helm chart
      run: |
        helm upgrade --install counter oci://${{ vars.ECR }} \
        --values ./infra/helm/values/counter.yaml --atomic \
        --version 1.0.0-${{ github.sha }} \
        --create-namespace --namespace default \
        --set image.tag=${{ github.sha }}